// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reactivities.Persistance;

#nullable disable

namespace Reactivities.Persistance.Migrations
{
    [DbContext(typeof(ReactivitiesDataContext))]
    partial class ReactivitiesDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Reactivities.Domain.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2022, 8, 1, 16, 28, 37, 400, DateTimeKind.Local).AddTicks(1013),
                            Description = "Activity 2 months ago",
                            IsCancelled = false,
                            Title = "Past Activity 1",
                            Venue = "Pub"
                        },
                        new
                        {
                            Id = 2,
                            Category = "culture",
                            City = "Paris",
                            Date = new DateTime(2022, 9, 1, 16, 28, 37, 400, DateTimeKind.Local).AddTicks(1028),
                            Description = "Activity 1 month ago",
                            IsCancelled = false,
                            Title = "Past Activity 2",
                            Venue = "The Louvre"
                        },
                        new
                        {
                            Id = 3,
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2022, 11, 1, 16, 28, 37, 400, DateTimeKind.Local).AddTicks(1031),
                            Description = "Activity 1 month in future",
                            IsCancelled = false,
                            Title = "Future Activity 1",
                            Venue = "Wembly Stadium"
                        },
                        new
                        {
                            Id = 4,
                            Category = "food",
                            City = "London",
                            Date = new DateTime(2022, 12, 1, 16, 28, 37, 400, DateTimeKind.Local).AddTicks(1033),
                            Description = "Activity 2 months in future",
                            IsCancelled = false,
                            Title = "Future Activity 2",
                            Venue = "Jamies Italian"
                        },
                        new
                        {
                            Id = 5,
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2023, 1, 1, 16, 28, 37, 400, DateTimeKind.Local).AddTicks(1035),
                            Description = "Activity 3 months in future",
                            IsCancelled = false,
                            Title = "Future Activity 3",
                            Venue = "Pub"
                        },
                        new
                        {
                            Id = 6,
                            Category = "culture",
                            City = "London",
                            Date = new DateTime(2023, 2, 1, 16, 28, 37, 400, DateTimeKind.Local).AddTicks(1036),
                            Description = "Activity 4 months in future",
                            IsCancelled = false,
                            Title = "Future Activity 4",
                            Venue = "British Museum"
                        },
                        new
                        {
                            Id = 7,
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2023, 3, 1, 16, 28, 37, 400, DateTimeKind.Local).AddTicks(1038),
                            Description = "Activity 5 months in future",
                            IsCancelled = false,
                            Title = "Future Activity 5",
                            Venue = "Punch and Judy"
                        },
                        new
                        {
                            Id = 8,
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2023, 4, 1, 16, 28, 37, 400, DateTimeKind.Local).AddTicks(1040),
                            Description = "Activity 6 months in future",
                            IsCancelled = false,
                            Title = "Future Activity 6",
                            Venue = "O2 Arena"
                        },
                        new
                        {
                            Id = 9,
                            Category = "travel",
                            City = "Berlin",
                            Date = new DateTime(2023, 5, 1, 16, 28, 37, 400, DateTimeKind.Local).AddTicks(1042),
                            Description = "Activity 7 months in future",
                            IsCancelled = false,
                            Title = "Future Activity 7",
                            Venue = "All"
                        },
                        new
                        {
                            Id = 10,
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2023, 6, 1, 16, 28, 37, 400, DateTimeKind.Local).AddTicks(1043),
                            Description = "Activity 8 months in future",
                            IsCancelled = false,
                            Title = "Future Activity 8",
                            Venue = "Pub"
                        });
                });

            modelBuilder.Entity("Reactivities.Domain.ActivityAttendee", b =>
                {
                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsHost")
                        .HasColumnType("bit");

                    b.HasKey("ActivityId", "AppUserId");

                    b.HasIndex("AppUserId");

                    b.ToTable("ActivityAttendees");

                    b.HasData(
                        new
                        {
                            ActivityId = 2,
                            AppUserId = "7D891E0A-E166-45E7-9F15-AE1F683EA43A",
                            IsHost = true
                        },
                        new
                        {
                            ActivityId = 2,
                            AppUserId = "72CC07A3-65A5-47DD-82A3-06F313FC12A7",
                            IsHost = false
                        },
                        new
                        {
                            ActivityId = 3,
                            AppUserId = "B61171D5-4848-4F3F-B425-EDECCB408C9B",
                            IsHost = true
                        },
                        new
                        {
                            ActivityId = 3,
                            AppUserId = "72CC07A3-65A5-47DD-82A3-06F313FC12A7",
                            IsHost = false
                        },
                        new
                        {
                            ActivityId = 4,
                            AppUserId = "7D891E0A-E166-45E7-9F15-AE1F683EA43A",
                            IsHost = true
                        },
                        new
                        {
                            ActivityId = 4,
                            AppUserId = "B61171D5-4848-4F3F-B425-EDECCB408C9B",
                            IsHost = false
                        },
                        new
                        {
                            ActivityId = 5,
                            AppUserId = "72CC07A3-65A5-47DD-82A3-06F313FC12A7",
                            IsHost = true
                        },
                        new
                        {
                            ActivityId = 5,
                            AppUserId = "7D891E0A-E166-45E7-9F15-AE1F683EA43A",
                            IsHost = false
                        },
                        new
                        {
                            ActivityId = 6,
                            AppUserId = "72CC07A3-65A5-47DD-82A3-06F313FC12A7",
                            IsHost = true
                        },
                        new
                        {
                            ActivityId = 7,
                            AppUserId = "7D891E0A-E166-45E7-9F15-AE1F683EA43A",
                            IsHost = true
                        },
                        new
                        {
                            ActivityId = 7,
                            AppUserId = "72CC07A3-65A5-47DD-82A3-06F313FC12A7",
                            IsHost = false
                        },
                        new
                        {
                            ActivityId = 8,
                            AppUserId = "B61171D5-4848-4F3F-B425-EDECCB408C9B",
                            IsHost = true
                        },
                        new
                        {
                            ActivityId = 8,
                            AppUserId = "72CC07A3-65A5-47DD-82A3-06F313FC12A7",
                            IsHost = false
                        },
                        new
                        {
                            ActivityId = 9,
                            AppUserId = "7D891E0A-E166-45E7-9F15-AE1F683EA43A",
                            IsHost = true
                        },
                        new
                        {
                            ActivityId = 9,
                            AppUserId = "B61171D5-4848-4F3F-B425-EDECCB408C9B",
                            IsHost = false
                        },
                        new
                        {
                            ActivityId = 10,
                            AppUserId = "B61171D5-4848-4F3F-B425-EDECCB408C9B",
                            IsHost = true
                        },
                        new
                        {
                            ActivityId = 10,
                            AppUserId = "72CC07A3-65A5-47DD-82A3-06F313FC12A7",
                            IsHost = false
                        });
                });

            modelBuilder.Entity("Reactivities.Domain.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "7D891E0A-E166-45E7-9F15-AE1F683EA43A",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6e060bfb-b81e-4520-82a7-b12c688aa4e7",
                            DisplayName = "Bob",
                            Email = "bob@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BOB@EXAMPLE.COM",
                            NormalizedUserName = "BOB@EXAMPLE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEGVHbH9gxxA/vknwPDR+2qPtQEpkwG/cQ5bbp+sLXwoUjQLOXS9sLgE7uMUGRKYs3w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dc5a5912-fa98-4506-9645-d42b296ac0bf",
                            TwoFactorEnabled = false,
                            UserName = "bob@example.com"
                        },
                        new
                        {
                            Id = "72CC07A3-65A5-47DD-82A3-06F313FC12A7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "89412066-f6b5-4e3b-8c93-a0e66dd5bb2e",
                            DisplayName = "Jane",
                            Email = "jane@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "JANE@EXAMPLE.COM",
                            NormalizedUserName = "JANE@EXAMPLE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEO4SLxzPIBtVT04HWuzhlGDp5s7iz1kSMyYYfxoHyq1QZxXcdQsTnWfPEfcST+tmtQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "50300cbe-8e80-4b93-8750-71e49ca58a8a",
                            TwoFactorEnabled = false,
                            UserName = "jane@example.com"
                        },
                        new
                        {
                            Id = "B61171D5-4848-4F3F-B425-EDECCB408C9B",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "62ad0132-e4af-4303-b95f-81c34b328670",
                            DisplayName = "Tom",
                            Email = "tom@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "TOM@EXAMPLE.COM",
                            NormalizedUserName = "TOM@EXAMPLE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEAmnpwmJRn4YmtoTTXCp8HpB8Ma7+AOloisx8SSIq27RG7EKwbDPHHObnenY8t4D8w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4addb173-881e-4bc9-8cf0-3a768dfbf833",
                            TwoFactorEnabled = false,
                            UserName = "tom@example.com"
                        });
                });

            modelBuilder.Entity("Reactivities.Domain.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<string>("AuthorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Reactivities.Domain.Photo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("Reactivities.Domain.UserFollowing", b =>
                {
                    b.Property<string>("ObserverId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TargetId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ObserverId", "TargetId");

                    b.HasIndex("TargetId");

                    b.ToTable("UserFollowings");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Reactivities.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Reactivities.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reactivities.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Reactivities.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reactivities.Domain.ActivityAttendee", b =>
                {
                    b.HasOne("Reactivities.Domain.Activity", "Activity")
                        .WithMany("Attendees")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reactivities.Domain.AppUser", "AppUser")
                        .WithMany("Activities")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Reactivities.Domain.Comment", b =>
                {
                    b.HasOne("Reactivities.Domain.Activity", "Activity")
                        .WithMany("Comments")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reactivities.Domain.AppUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.Navigation("Activity");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Reactivities.Domain.Photo", b =>
                {
                    b.HasOne("Reactivities.Domain.AppUser", null)
                        .WithMany("Photos")
                        .HasForeignKey("AppUserId");
                });

            modelBuilder.Entity("Reactivities.Domain.UserFollowing", b =>
                {
                    b.HasOne("Reactivities.Domain.AppUser", "Observer")
                        .WithMany("Followers")
                        .HasForeignKey("ObserverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Reactivities.Domain.AppUser", "Target")
                        .WithMany("Followings")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Observer");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("Reactivities.Domain.Activity", b =>
                {
                    b.Navigation("Attendees");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Reactivities.Domain.AppUser", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Followers");

                    b.Navigation("Followings");

                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
